SET(CMAKE_SYSTEM_NAME        Windows)
SET(CMAKE_SYSTEM_VERSION     1)

SET(CMAKE_SYSTEM_PROCESSOR          x86_64)
SET(CMAKE_SYSTEM_PROCESSOR32        i686)

SET(WIN64                           TRUE)
