#-------------------------------------------------
#
# Project created by QtCreator 2020-01-19T00:22:50
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = QT-SDL
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

#win32:INCLUDEPATH+=C:\Users\TEST\Downloads\irrlicht-1.8.4\irrlicht-1.8.4\include
#else:unix:INCLUDEPATH+= /home/Dev/libs/game/irrlicht/Irrlicht-SVN/include/ /home/Dev/libs/game/irrlicht/Irrlicht-SVN/lib/Linux/

win32:LIBS += -LC:\Users\TEST\Downloads\irrlicht-1.8.4\irrlicht-1.8.4\lib\Win32-visualstudio
else:unix:LIBS += -L/home/Dev/libs/game/irrlicht/Irrlicht-SVN/lib/Linux/ -lSDL2 -lSDL2_image#-lSDLmain


SOURCES += \
    main.cpp \
    mainwindow.cpp \
    plugins/Amplifier/Amplifier.cpp \
    plugins/Amplifier/AmplifierControlDialog.cpp \
    plugins/Amplifier/AmplifierControls.cpp \
    plugins/audio_file_processor/audio_file_processor.cpp \
    plugins/BassBooster/BassBooster.cpp \
    plugins/BassBooster/BassBoosterControlDialog.cpp \
    plugins/BassBooster/BassBoosterControls.cpp \
    plugins/bit_invader/bit_invader.cpp \
    plugins/Bitcrush/Bitcrush.cpp \
    plugins/Bitcrush/BitcrushControlDialog.cpp \
    plugins/Bitcrush/BitcrushControls.cpp \
    plugins/carlabase/carla.cpp \
    plugins/carlabase/moc_carla.cpp \
    plugins/carlabase/qrc_carlabase.cpp \
    plugins/carlapatchbay/carlapatchbay.cpp \
    plugins/carlarack/carlarack.cpp \
    plugins/CrossoverEQ/CrossoverEQ.cpp \
    plugins/CrossoverEQ/CrossoverEQControlDialog.cpp \
    plugins/CrossoverEQ/CrossoverEQControls.cpp \
    plugins/Delay/DelayControls.cpp \
    plugins/Delay/DelayControlsDialog.cpp \
    plugins/Delay/DelayEffect.cpp \
    plugins/Delay/Lfo.cpp \
    plugins/Delay/StereoDelay.cpp \
    plugins/DualFilter/DualFilter.cpp \
    plugins/DualFilter/DualFilterControlDialog.cpp \
    plugins/DualFilter/DualFilterControls.cpp \
    plugins/dynamics_processor/dynamics_processor.cpp \
    plugins/dynamics_processor/dynamics_processor_control_dialog.cpp \
    plugins/dynamics_processor/dynamics_processor_controls.cpp \
    plugins/Eq/EqControls.cpp \
    plugins/Eq/EqControlsDialog.cpp \
    plugins/Eq/EqCurve.cpp \
    plugins/Eq/EqEffect.cpp \
    plugins/Eq/EqParameterWidget.cpp \
    plugins/Eq/EqSpectrumView.cpp \
    plugins/Flanger/FlangerControls.cpp \
    plugins/Flanger/FlangerControlsDialog.cpp \
    plugins/Flanger/FlangerEffect.cpp \
    plugins/Flanger/MonoDelay.cpp \
    plugins/Flanger/Noise.cpp \
    plugins/Flanger/QuadratureLfo.cpp \
    plugins/FreeBoy/game-music-emu/demo/cpp_basics.cpp \
    plugins/FreeBoy/game-music-emu/demo/Wave_Writer.cpp \
    plugins/FreeBoy/game-music-emu/gme/Ay_Apu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Ay_Cpu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Ay_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Blip_Buffer.cpp \
    plugins/FreeBoy/game-music-emu/gme/Classic_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Data_Reader.cpp \
    plugins/FreeBoy/game-music-emu/gme/Dual_Resampler.cpp \
    plugins/FreeBoy/game-music-emu/gme/Effects_Buffer.cpp \
    plugins/FreeBoy/game-music-emu/gme/Fir_Resampler.cpp \
    plugins/FreeBoy/game-music-emu/gme/Gb_Apu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Gb_Cpu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Gb_Oscs.cpp \
    plugins/FreeBoy/game-music-emu/gme/Gbs_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/gme.cpp \
    plugins/FreeBoy/game-music-emu/gme/Gme_File.cpp \
    plugins/FreeBoy/game-music-emu/gme/Gym_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Hes_Apu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Hes_Cpu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Hes_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Kss_Cpu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Kss_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Kss_Scc_Apu.cpp \
    plugins/FreeBoy/game-music-emu/gme/M3u_Playlist.cpp \
    plugins/FreeBoy/game-music-emu/gme/Multi_Buffer.cpp \
    plugins/FreeBoy/game-music-emu/gme/Music_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Nes_Apu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Nes_Cpu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Nes_Fme7_Apu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Nes_Namco_Apu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Nes_Oscs.cpp \
    plugins/FreeBoy/game-music-emu/gme/Nes_Vrc6_Apu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Nsf_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Nsfe_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Sap_Apu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Sap_Cpu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Sap_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Sms_Apu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Snes_Spc.cpp \
    plugins/FreeBoy/game-music-emu/gme/Spc_Cpu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Spc_Dsp.cpp \
    plugins/FreeBoy/game-music-emu/gme/Spc_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Spc_Filter.cpp \
    plugins/FreeBoy/game-music-emu/gme/Vgm_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Vgm_Emu_Impl.cpp \
    plugins/FreeBoy/game-music-emu/gme/Ym2413_Emu.cpp \
    plugins/FreeBoy/game-music-emu/gme/Ym2612_Emu.cpp \
    plugins/FreeBoy/game-music-emu/player/Audio_Scope.cpp \
    plugins/FreeBoy/game-music-emu/player/Music_Player.cpp \
    plugins/FreeBoy/game-music-emu/player/player.cpp \
    plugins/FreeBoy/game-music-emu/test/Wave_Writer.cpp \
    plugins/FreeBoy/FreeBoy.cpp \
    plugins/FreeBoy/Gb_Apu_Buffer.cpp \
    plugins/GigPlayer/GigPlayer.cpp \
    plugins/GigPlayer/PatchesDialog.cpp \
    plugins/HydrogenImport/HydrogenImport.cpp \
    plugins/HydrogenImport/local_file_mgr.cpp \
    plugins/kicker/kicker.cpp \
    plugins/ladspa_browser/ladspa_browser.cpp \
    plugins/ladspa_browser/ladspa_description.cpp \
    plugins/ladspa_browser/ladspa_port_dialog.cpp \
    plugins/LadspaEffect/calf/veal/bigbull/calfpytools.cpp \
    plugins/LadspaEffect/calf/veal/src/analyzer.cpp \
    plugins/LadspaEffect/calf/veal/src/audio_fx.cpp \
    plugins/LadspaEffect/calf/veal/src/benchmark.cpp \
    plugins/LadspaEffect/calf/veal/src/connector.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_buttons.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_combobox.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_curve.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_fader.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_frame.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_keyboard.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_knob.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_led.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_linegraph.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_meterscale.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_notebook.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_pattern.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_phasegraph.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_tube.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_tuner.cpp \
    plugins/LadspaEffect/calf/veal/src/ctl_vumeter.cpp \
    plugins/LadspaEffect/calf/veal/src/drawingutils.cpp \
    plugins/LadspaEffect/calf/veal/src/fluidsynth.cpp \
    plugins/LadspaEffect/calf/veal/src/giface.cpp \
    plugins/LadspaEffect/calf/veal/src/gtk_main_win.cpp \
    plugins/LadspaEffect/calf/veal/src/gtk_session_env.cpp \
    plugins/LadspaEffect/calf/veal/src/gui.cpp \
    plugins/LadspaEffect/calf/veal/src/gui_config.cpp \
    plugins/LadspaEffect/calf/veal/src/gui_controls.cpp \
    plugins/LadspaEffect/calf/veal/src/host_session.cpp \
    plugins/LadspaEffect/calf/veal/src/jack_client.cpp \
    plugins/LadspaEffect/calf/veal/src/jackhost.cpp \
    plugins/LadspaEffect/calf/veal/src/lv2gui.cpp \
    plugins/LadspaEffect/calf/veal/src/lv2wrap.cpp \
    plugins/LadspaEffect/calf/veal/src/makerdf.cpp \
    plugins/LadspaEffect/calf/veal/src/metadata.cpp \
    plugins/LadspaEffect/calf/veal/src/modmatrix.cpp \
    plugins/LadspaEffect/calf/veal/src/modules_comp.cpp \
    plugins/LadspaEffect/calf/veal/src/modules_delay.cpp \
    plugins/LadspaEffect/calf/veal/src/modules_dist.cpp \
    plugins/LadspaEffect/calf/veal/src/modules_filter.cpp \
    plugins/LadspaEffect/calf/veal/src/modules_limit.cpp \
    plugins/LadspaEffect/calf/veal/src/modules_mod.cpp \
    plugins/LadspaEffect/calf/veal/src/modules_pitch.cpp \
    plugins/LadspaEffect/calf/veal/src/modules_tools.cpp \
    plugins/LadspaEffect/calf/veal/src/monosynth.cpp \
    plugins/LadspaEffect/calf/veal/src/organ.cpp \
    plugins/LadspaEffect/calf/veal/src/osctl.cpp \
    plugins/LadspaEffect/calf/veal/src/plugin.cpp \
    plugins/LadspaEffect/calf/veal/src/plugin_gui_window.cpp \
    plugins/LadspaEffect/calf/veal/src/preset.cpp \
    plugins/LadspaEffect/calf/veal/src/preset_gui.cpp \
    plugins/LadspaEffect/calf/veal/src/session_mgr.cpp \
    plugins/LadspaEffect/calf/veal/src/synth.cpp \
    plugins/LadspaEffect/calf/veal/src/utils.cpp \
    plugins/LadspaEffect/calf/veal/src/veal.cpp \
    plugins/LadspaEffect/calf/veal/src/wavetable.cpp \
    plugins/LadspaEffect/caps/Amp.cc \
    plugins/LadspaEffect/caps/Cabinet.cc \
    plugins/LadspaEffect/caps/Chorus.cc \
    plugins/LadspaEffect/caps/Click.cc \
    plugins/LadspaEffect/caps/Clip.cc \
    plugins/LadspaEffect/caps/Compress.cc \
    plugins/LadspaEffect/caps/Eq.cc \
    plugins/LadspaEffect/caps/HRTF.cc \
    plugins/LadspaEffect/caps/interface.cc \
    plugins/LadspaEffect/caps/Lorenz.cc \
    plugins/LadspaEffect/caps/Pan.cc \
    plugins/LadspaEffect/caps/Phaser.cc \
    plugins/LadspaEffect/caps/Preamp.cc \
    plugins/LadspaEffect/caps/Reverb.cc \
    plugins/LadspaEffect/caps/Roessler.cc \
    plugins/LadspaEffect/caps/Scape.cc \
    plugins/LadspaEffect/caps/Sin.cc \
    plugins/LadspaEffect/caps/SweepVF.cc \
    plugins/LadspaEffect/caps/ToneControls.cc \
    plugins/LadspaEffect/caps/ToneStack.cc \
    plugins/LadspaEffect/caps/VCO.cc \
    plugins/LadspaEffect/caps/White.cc \
    plugins/LadspaEffect/cmt/src/freeverb/Components/allpass.cpp \
    plugins/LadspaEffect/cmt/src/freeverb/Components/comb.cpp \
    plugins/LadspaEffect/cmt/src/freeverb/Components/revmodel.cpp \
    plugins/LadspaEffect/cmt/src/freeverb/freeverb.cpp \
    plugins/LadspaEffect/cmt/src/am.cpp \
    plugins/LadspaEffect/cmt/src/ambisonic.cpp \
    plugins/LadspaEffect/cmt/src/amp.cpp \
    plugins/LadspaEffect/cmt/src/analogue.cpp \
    plugins/LadspaEffect/cmt/src/canyondelay.cpp \
    plugins/LadspaEffect/cmt/src/cmt.cpp \
    plugins/LadspaEffect/cmt/src/delay.cpp \
    plugins/LadspaEffect/cmt/src/descriptor.cpp \
    plugins/LadspaEffect/cmt/src/disintegrator.cpp \
    plugins/LadspaEffect/cmt/src/dynamic.cpp \
    plugins/LadspaEffect/cmt/src/filter.cpp \
    plugins/LadspaEffect/cmt/src/grain.cpp \
    plugins/LadspaEffect/cmt/src/hardgate.cpp \
    plugins/LadspaEffect/cmt/src/init.cpp \
    plugins/LadspaEffect/cmt/src/lofi.cpp \
    plugins/LadspaEffect/cmt/src/logistic.cpp \
    plugins/LadspaEffect/cmt/src/mixer.cpp \
    plugins/LadspaEffect/cmt/src/noise.cpp \
    plugins/LadspaEffect/cmt/src/null.cpp \
    plugins/LadspaEffect/cmt/src/organ.cpp \
    plugins/LadspaEffect/cmt/src/peak.cpp \
    plugins/LadspaEffect/cmt/src/phasemod.cpp \
    plugins/LadspaEffect/cmt/src/pink.cpp \
    plugins/LadspaEffect/cmt/src/pink_full.cpp \
    plugins/LadspaEffect/cmt/src/pink_sh.cpp \
    plugins/LadspaEffect/cmt/src/sine.cpp \
    plugins/LadspaEffect/cmt/src/sledgehammer.cpp \
    plugins/LadspaEffect/cmt/src/syndrum.cpp \
    plugins/LadspaEffect/cmt/src/vcf303.cpp \
    plugins/LadspaEffect/cmt/src/wshape_sine.cpp \
    plugins/LadspaEffect/LadspaControlDialog.cpp \
    plugins/LadspaEffect/LadspaControls.cpp \
    plugins/LadspaEffect/LadspaEffect.cpp \
    plugins/LadspaEffect/LadspaSubPluginFeatures.cpp \
    plugins/lb302/lb302.cpp \
    plugins/MidiExport/MidiExport.cpp \
    plugins/MidiImport/portsmf/allegro.cpp \
    plugins/MidiImport/portsmf/allegrord.cpp \
    plugins/MidiImport/portsmf/allegroserial.cpp \
    plugins/MidiImport/portsmf/allegrosmfrd.cpp \
    plugins/MidiImport/portsmf/allegrosmfwr.cpp \
    plugins/MidiImport/portsmf/allegrowr.cpp \
    plugins/MidiImport/portsmf/mfmidi.cpp \
    plugins/MidiImport/portsmf/strparse.cpp \
    plugins/MidiImport/portsmf/trace.cpp \
    plugins/MidiImport/MidiImport.cpp \
    plugins/monstro/Monstro.cpp \
    plugins/MultitapEcho/MultitapEcho.cpp \
    plugins/MultitapEcho/MultitapEchoControlDialog.cpp \
    plugins/MultitapEcho/MultitapEchoControls.cpp \
    plugins/nes/Nes.cpp \
    plugins/OpulenZ/adplug/adplugdb/adplugdb.cpp \
    plugins/OpulenZ/adplug/src/a2m.cpp \
    plugins/OpulenZ/adplug/src/adl.cpp \
    plugins/OpulenZ/adplug/src/adlib.cpp \
    plugins/OpulenZ/adplug/src/adplug.cpp \
    plugins/OpulenZ/adplug/src/adtrack.cpp \
    plugins/OpulenZ/adplug/src/amd.cpp \
    plugins/OpulenZ/adplug/src/analopl.cpp \
    plugins/OpulenZ/adplug/src/bam.cpp \
    plugins/OpulenZ/adplug/src/bmf.cpp \
    plugins/OpulenZ/adplug/src/cff.cpp \
    plugins/OpulenZ/adplug/src/cmf.cpp \
    plugins/OpulenZ/adplug/src/cmfmcsop.cpp \
    plugins/OpulenZ/adplug/src/d00.cpp \
    plugins/OpulenZ/adplug/src/database.cpp \
    plugins/OpulenZ/adplug/src/dfm.cpp \
    plugins/OpulenZ/adplug/src/diskopl.cpp \
    plugins/OpulenZ/adplug/src/dmo.cpp \
    plugins/OpulenZ/adplug/src/dro.cpp \
    plugins/OpulenZ/adplug/src/dro2.cpp \
    plugins/OpulenZ/adplug/src/dtm.cpp \
    plugins/OpulenZ/adplug/src/emuopl.cpp \
    plugins/OpulenZ/adplug/src/flash.cpp \
    plugins/OpulenZ/adplug/src/fmc.cpp \
    plugins/OpulenZ/adplug/src/fprovide.cpp \
    plugins/OpulenZ/adplug/src/got.cpp \
    plugins/OpulenZ/adplug/src/hsc.cpp \
    plugins/OpulenZ/adplug/src/hsp.cpp \
    plugins/OpulenZ/adplug/src/hybrid.cpp \
    plugins/OpulenZ/adplug/src/hyp.cpp \
    plugins/OpulenZ/adplug/src/imf.cpp \
    plugins/OpulenZ/adplug/src/jbm.cpp \
    plugins/OpulenZ/adplug/src/ksm.cpp \
    plugins/OpulenZ/adplug/src/lds.cpp \
    plugins/OpulenZ/adplug/src/mad.cpp \
    plugins/OpulenZ/adplug/src/mdi.cpp \
    plugins/OpulenZ/adplug/src/mid.cpp \
    plugins/OpulenZ/adplug/src/mkj.cpp \
    plugins/OpulenZ/adplug/src/msc.cpp \
    plugins/OpulenZ/adplug/src/mtk.cpp \
    plugins/OpulenZ/adplug/src/mus.cpp \
    plugins/OpulenZ/adplug/src/nemuopl.cpp \
    plugins/OpulenZ/adplug/src/player.cpp \
    plugins/OpulenZ/adplug/src/players.cpp \
    plugins/OpulenZ/adplug/src/protrack.cpp \
    plugins/OpulenZ/adplug/src/psi.cpp \
    plugins/OpulenZ/adplug/src/rad.cpp \
    plugins/OpulenZ/adplug/src/rat.cpp \
    plugins/OpulenZ/adplug/src/raw.cpp \
    plugins/OpulenZ/adplug/src/realopl.cpp \
    plugins/OpulenZ/adplug/src/rix.cpp \
    plugins/OpulenZ/adplug/src/rol.cpp \
    plugins/OpulenZ/adplug/src/s3m.cpp \
    plugins/OpulenZ/adplug/src/sa2.cpp \
    plugins/OpulenZ/adplug/src/sng.cpp \
    plugins/OpulenZ/adplug/src/sop.cpp \
    plugins/OpulenZ/adplug/src/surroundopl.cpp \
    plugins/OpulenZ/adplug/src/temuopl.cpp \
    plugins/OpulenZ/adplug/src/u6m.cpp \
    plugins/OpulenZ/adplug/src/vgm.cpp \
    plugins/OpulenZ/adplug/src/woodyopl.cpp \
    plugins/OpulenZ/adplug/src/xad.cpp \
    plugins/OpulenZ/adplug/src/xsm.cpp \
    plugins/OpulenZ/adplug/test/crctest.cpp \
    plugins/OpulenZ/adplug/test/emutest.cpp \
    plugins/OpulenZ/adplug/test/playertest.cpp \
    plugins/OpulenZ/OpulenZ.cpp \
    plugins/organic/organic.cpp \
    plugins/patman/patman.cpp \
    plugins/peak_controller_effect/peak_controller_effect.cpp \
    plugins/peak_controller_effect/peak_controller_effect_control_dialog.cpp \
    plugins/peak_controller_effect/peak_controller_effect_controls.cpp \
    plugins/ReverbSC/ReverbSC.cpp \
    plugins/ReverbSC/ReverbSCControlDialog.cpp \
    plugins/ReverbSC/ReverbSCControls.cpp \
    plugins/sf2_player/patches_dialog.cpp \
    plugins/sf2_player/sf2_player.cpp \
    plugins/sfxr/sfxr.cpp \
    plugins/sid/envelope.cc \
    plugins/sid/extfilt.cc \
    plugins/sid/filter.cc \
    plugins/sid/pot.cc \
    plugins/sid/sid.cc \
    plugins/sid/sid_instrument.cpp \
    plugins/sid/version.cc \
    plugins/sid/voice.cc \
    plugins/sid/wave.cc \
    plugins/sid/wave6581__ST.cc \
    plugins/sid/wave6581_P_T.cc \
    plugins/sid/wave6581_PS_.cc \
    plugins/sid/wave6581_PST.cc \
    plugins/sid/wave8580__ST.cc \
    plugins/sid/wave8580_P_T.cc \
    plugins/sid/wave8580_PS_.cc \
    plugins/sid/wave8580_PST.cc \
    plugins/SpectrumAnalyzer/Analyzer.cpp \
    plugins/SpectrumAnalyzer/moc_SpectrumAnalyzerControlDialog.cpp \
    plugins/SpectrumAnalyzer/moc_SpectrumAnalyzerControls.cpp \
    plugins/SpectrumAnalyzer/qrc_spectrumanalyzer.cpp \
    plugins/SpectrumAnalyzer/SaControls.cpp \
    plugins/SpectrumAnalyzer/SaControlsDialog.cpp \
    plugins/SpectrumAnalyzer/SaProcessor.cpp \
    plugins/SpectrumAnalyzer/SaSpectrumView.cpp \
    plugins/SpectrumAnalyzer/SaWaterfallView.cpp \
    plugins/stereo_enhancer/stereo_enhancer.cpp \
    plugins/stereo_enhancer/stereoenhancer_control_dialog.cpp \
    plugins/stereo_enhancer/stereoenhancer_controls.cpp \
    plugins/stereo_matrix/stereo_matrix.cpp \
    plugins/stereo_matrix/stereomatrix_control_dialog.cpp \
    plugins/stereo_matrix/stereomatrix_controls.cpp \
    plugins/stk/mallets/mallets.cpp \
    plugins/stk/mallets/moc_mallets.cpp \
    plugins/stk/mallets/qrc_malletsstk.cpp \
    plugins/triple_oscillator/TripleOscillator.cpp \
    plugins/vestige/vestige.cpp \
    plugins/vibed/nine_button_selector.cpp \
    plugins/vibed/string_container.cpp \
    plugins/vibed/vibed.cpp \
    plugins/vibed/vibrating_string.cpp \
    plugins/vst_base/RemoteVstPlugin32-prefix/src/RemoteVstPlugin32-build/CMakeFiles/3.10.2/CompilerIdCXX/CMakeCXXCompilerId.cpp \
    plugins/vst_base/RemoteVstPlugin64-prefix/src/RemoteVstPlugin64-build/CMakeFiles/3.10.2/CompilerIdCXX/CMakeCXXCompilerId.cpp \
    plugins/vst_base/RemoteVstPlugin64-prefix/src/RemoteVstPlugin64-build/CMakeFiles/feature_tests.cxx \
    plugins/vst_base/RemoteVstPlugin64-prefix/src/RemoteVstPlugin64-build/CxxTmp/src.cpp \
    plugins/vst_base/RemoteVstPlugin.cpp \
    plugins/vst_base/vst_base.cpp \
    plugins/vst_base/VstPlugin.cpp \
    plugins/VstEffect/VstEffect.cpp \
    plugins/VstEffect/VstEffectControlDialog.cpp \
    plugins/VstEffect/VstEffectControls.cpp \
    plugins/VstEffect/VstSubPluginFeatures.cpp \
    plugins/watsyn/Watsyn.cpp \
    plugins/waveshaper/waveshaper.cpp \
    plugins/waveshaper/waveshaper_control_dialog.cpp \
    plugins/waveshaper/waveshaper_controls.cpp \
    plugins/Xpressive/exprtk/exprtk_benchmark.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_01.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_02.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_03.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_04.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_05.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_06.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_07.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_08.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_09.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_10.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_11.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_12.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_13.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_14.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_15.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_16.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_17.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_18.cpp \
    plugins/Xpressive/exprtk/exprtk_simple_example_19.cpp \
    plugins/Xpressive/exprtk/exprtk_test.cpp \
    plugins/Xpressive/ExprSynth.cpp \
    plugins/Xpressive/Xpressive.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/DSP/AnalogFilter.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/DSP/FFTwrapper.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/DSP/Filter.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/DSP/FormantFilter.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/DSP/SVFilter.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/DSP/Unison.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Alienwah.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Chorus.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Distorsion.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/DynamicFilter.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Echo.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Effect.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/EffectLFO.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/EffectMgr.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/EQ.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Phaser.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Reverb.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Bank.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Config.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Dump.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/LASHClient.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Master.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Microtonal.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Part.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/QtXmlWrapper.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Recorder.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Stereo.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Util.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/WaveShapeSmps.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/WavFile.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/XMLwrapper.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/AlsaEngine.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/AudioOut.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/Engine.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/EngineMgr.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/InMgr.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/JackEngine.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/MidiIn.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/Nio.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/NulEngine.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/OssEngine.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/OutMgr.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/PaEngine.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/SafeQueue.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/WavEngine.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Output/DSSIaudiooutput.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/ADnoteParameters.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/Controller.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/EnvelopeParams.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/FilterParams.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/LFOParams.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/PADnoteParameters.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/Presets.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/PresetsArray.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/PresetsStore.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/SUBnoteParameters.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/ADnote.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/Envelope.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/LFO.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/OscilGen.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/PADnote.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/Resonance.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/SUBnote.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/SynthNote.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/UI/NioUI.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/UI/WidgetPDial.cpp \
    plugins/zynaddsubfx/zynaddsubfx/src/main.cpp \
    plugins/zynaddsubfx/LocalZynAddSubFx.cpp \
    plugins/zynaddsubfx/RemoteZynAddSubFx.cpp \
    plugins/zynaddsubfx/ZynAddSubFx.cpp \
    src/core/audio/AudioAlsa.cpp \
    src/core/audio/AudioDevice.cpp \
    src/core/audio/AudioFileDevice.cpp \
    src/core/audio/AudioFileFlac.cpp \
    src/core/audio/AudioFileMP3.cpp \
    src/core/audio/AudioFileOgg.cpp \
    src/core/audio/AudioFileWave.cpp \
    src/core/audio/AudioJack.cpp \
    src/core/audio/AudioOss.cpp \
    src/core/audio/AudioPort.cpp \
    src/core/audio/AudioPortAudio.cpp \
    src/core/audio/AudioPulseAudio.cpp \
    src/core/audio/AudioSampleRecorder.cpp \
    src/core/audio/AudioSdl.cpp \
    src/core/audio/AudioSndio.cpp \
    src/core/audio/AudioSoundIo.cpp \
    src/core/midi/MidiAlsaRaw.cpp \
    src/core/midi/MidiAlsaSeq.cpp \
    src/core/midi/MidiApple.cpp \
    src/core/midi/MidiClient.cpp \
    src/core/midi/MidiController.cpp \
    src/core/midi/MidiJack.cpp \
    src/core/midi/MidiOss.cpp \
    src/core/midi/MidiPort.cpp \
    src/core/midi/MidiSndio.cpp \
    src/core/midi/MidiTime.cpp \
    src/core/midi/MidiWinMM.cpp \
    src/core/AutomatableModel.cpp \
    src/core/AutomationPattern.cpp \
    src/core/BandLimitedWave.cpp \
    src/core/base64.cpp \
    src/core/BBTrackContainer.cpp \
    src/core/BufferManager.cpp \
    src/core/Clipboard.cpp \
    src/core/ComboBoxModel.cpp \
    src/core/ConfigManager.cpp \
    src/core/Controller.cpp \
    src/core/ControllerConnection.cpp \
    src/core/DataFile.cpp \
    src/core/DrumSynth.cpp \
    src/core/Effect.cpp \
    src/core/EffectChain.cpp \
    src/core/Engine.cpp \
    src/core/EnvelopeAndLfoParameters.cpp \
    src/core/fft_helpers.cpp \
    src/core/FxMixer.cpp \
    src/core/ImportFilter.cpp \
    src/core/InlineAutomation.cpp \
    src/core/Instrument.cpp \
    src/core/InstrumentFunctions.cpp \
    src/core/InstrumentPlayHandle.cpp \
    src/core/InstrumentSoundShaping.cpp \
    src/core/JournallingObject.cpp \
    src/core/Ladspa2LMMS.cpp \
    src/core/LadspaControl.cpp \
    src/core/LadspaManager.cpp \
    src/core/LfoController.cpp \
    src/core/LocklessAllocator.cpp \
    src/core/main.cpp \
    src/core/MemoryHelper.cpp \
    src/core/MemoryManager.cpp \
    src/core/MeterModel.cpp \
    src/core/MicroTimer.cpp \
    src/core/Mixer.cpp \
    src/core/MixerProfiler.cpp \
    src/core/MixerWorkerThread.cpp \
    src/core/MixHelpers.cpp \
    src/core/Model.cpp \
    src/core/ModelVisitor.cpp \
    src/core/Note.cpp \
    src/core/NotePlayHandle.cpp \
    src/core/Oscillator.cpp \
    src/core/PeakController.cpp \
    src/core/PerfLog.cpp \
    src/core/Piano.cpp \
    src/core/PlayHandle.cpp \
    src/core/Plugin.cpp \
    src/core/PluginFactory.cpp \
    src/core/PluginIssue.cpp \
    src/core/PresetPreviewPlayHandle.cpp \
    src/core/ProjectJournal.cpp \
    src/core/ProjectRenderer.cpp \
    src/core/ProjectVersion.cpp \
    src/core/RemotePlugin.cpp \
    src/core/RenderManager.cpp \
    src/core/RingBuffer.cpp \
    src/core/SampleBuffer.cpp \
    src/core/SamplePlayHandle.cpp \
    src/core/SampleRecordHandle.cpp \
    src/core/SerializingObject.cpp \
    src/core/Song.cpp \
    src/core/StepRecorder.cpp \
    src/core/TempoSyncKnobModel.cpp \
    src/core/ToolPlugin.cpp \
    src/core/Track.cpp \
    src/core/TrackContainer.cpp \
    src/core/ValueBuffer.cpp \
    src/core/VstSyncController.cpp \
    src/gui/dialogs/FileDialog.cpp \
    src/gui/dialogs/VersionedSaveDialog.cpp \
    src/gui/editors/AutomationEditor.cpp \
    src/gui/editors/BBEditor.cpp \
    src/gui/editors/Editor.cpp \
    src/gui/editors/PianoRoll.cpp \
    src/gui/editors/SongEditor.cpp \
    src/gui/menus/RecentProjectsMenu.cpp \
    src/gui/menus/TemplatesMenu.cpp \
    src/gui/widgets/AutomatableButton.cpp \
    src/gui/widgets/AutomatableSlider.cpp \
    src/gui/widgets/CaptionMenu.cpp \
    src/gui/widgets/ComboBox.cpp \
    src/gui/widgets/ControllerRackView.cpp \
    src/gui/widgets/ControllerView.cpp \
    src/gui/widgets/CPULoadWidget.cpp \
    src/gui/widgets/EffectRackView.cpp \
    src/gui/widgets/EffectView.cpp \
    src/gui/widgets/EnvelopeAndLfoView.cpp \
    src/gui/widgets/FadeButton.cpp \
    src/gui/widgets/Fader.cpp \
    src/gui/widgets/FxLine.cpp \
    src/gui/widgets/FxLineLcdSpinBox.cpp \
    src/gui/widgets/Graph.cpp \
    src/gui/widgets/GroupBox.cpp \
    src/gui/widgets/InstrumentFunctionViews.cpp \
    src/gui/widgets/InstrumentMidiIOView.cpp \
    src/gui/widgets/InstrumentSoundShapingView.cpp \
    src/gui/widgets/Knob.cpp \
    src/gui/widgets/LadspaControlView.cpp \
    src/gui/widgets/LcdSpinBox.cpp \
    src/gui/widgets/LcdWidget.cpp \
    src/gui/widgets/LedCheckbox.cpp \
    src/gui/widgets/LeftRightNav.cpp \
    src/gui/widgets/MeterDialog.cpp \
    src/gui/widgets/MidiPortMenu.cpp \
    src/gui/widgets/NStateButton.cpp \
    src/gui/widgets/PixmapButton.cpp \
    src/gui/widgets/ProjectNotes.cpp \
    src/gui/widgets/RenameDialog.cpp \
    src/gui/widgets/Rubberband.cpp \
    src/gui/widgets/SendButtonIndicator.cpp \
    src/gui/widgets/SideBar.cpp \
    src/gui/widgets/SideBarWidget.cpp \
    src/gui/widgets/StepRecorderWidget.cpp \
    src/gui/widgets/TabBar.cpp \
    src/gui/widgets/TabWidget.cpp \
    src/gui/widgets/TempoSyncKnob.cpp \
    src/gui/widgets/TextFloat.cpp \
    src/gui/widgets/TimeDisplayWidget.cpp \
    src/gui/widgets/ToolButton.cpp \
    src/gui/widgets/ToolTip.cpp \
    src/gui/widgets/TrackLabelButton.cpp \
    src/gui/widgets/TrackRenameLineEdit.cpp \
    src/gui/widgets/VisualizationWidget.cpp \
    src/gui/AboutDialog.cpp \
    src/gui/ActionGroup.cpp \
    src/gui/AudioAlsaSetupWidget.cpp \
    src/gui/AudioDeviceSetupWidget.cpp \
    src/gui/AutomatableModelView.cpp \
    src/gui/AutomationPatternView.cpp \
    src/gui/ControllerConnectionDialog.cpp \
    src/gui/ControllerDialog.cpp \
    src/gui/EffectControlDialog.cpp \
    src/gui/EffectSelectDialog.cpp \
    src/gui/embed.cpp \
    src/gui/ExportProjectDialog.cpp \
    src/gui/FileBrowser.cpp \
    src/gui/FxMixerView.cpp \
    src/gui/GuiApplication.cpp \
    src/gui/InstrumentView.cpp \
    src/gui/LfoControllerDialog.cpp \
    src/gui/LmmsPalette.cpp \
    src/gui/LmmsStyle.cpp \
    src/gui/MainApplication.cpp \
    src/gui/MainWindow.cpp \
    src/gui/MidiSetupWidget.cpp \
    src/gui/ModelView.cpp \
    src/gui/PeakControllerDialog.cpp \
    src/gui/PianoView.cpp \
    src/gui/PluginBrowser.cpp \
    src/gui/RowTableView.cpp \
    src/gui/SetupDialog.cpp \
    src/gui/StringPairDrag.cpp \
    src/gui/SubWindow.cpp \
    src/gui/TimeLineWidget.cpp \
    src/gui/ToolPluginView.cpp \
    src/gui/TrackContainerView.cpp \
    src/tracks/AutomationTrack.cpp \
    src/tracks/BBTrack.cpp \
    src/tracks/InstrumentTrack.cpp \
    src/tracks/Pattern.cpp \
    src/tracks/SampleTrack.cpp \
    plugins/FreeBoy/game-music-emu/demo/basics.c \
    plugins/FreeBoy/game-music-emu/demo/features.c \
    plugins/FreeBoy/game-music-emu/test/basics.c \
    plugins/LadspaEffect/swh/ladspa/gsm/add.c \
    plugins/LadspaEffect/swh/ladspa/gsm/code.c \
    plugins/LadspaEffect/swh/ladspa/gsm/decode.c \
    plugins/LadspaEffect/swh/ladspa/gsm/gsm_create.c \
    plugins/LadspaEffect/swh/ladspa/gsm/gsm_decode.c \
    plugins/LadspaEffect/swh/ladspa/gsm/gsm_destroy.c \
    plugins/LadspaEffect/swh/ladspa/gsm/gsm_encode.c \
    plugins/LadspaEffect/swh/ladspa/gsm/gsm_option.c \
    plugins/LadspaEffect/swh/ladspa/gsm/long_term.c \
    plugins/LadspaEffect/swh/ladspa/gsm/lpc.c \
    plugins/LadspaEffect/swh/ladspa/gsm/preprocess.c \
    plugins/LadspaEffect/swh/ladspa/gsm/rpe.c \
    plugins/LadspaEffect/swh/ladspa/gsm/short_term.c \
    plugins/LadspaEffect/swh/ladspa/gsm/table.c \
    plugins/LadspaEffect/swh/ladspa/gverb/gverb-test.c \
    plugins/LadspaEffect/swh/ladspa/gverb/gverb.c \
    plugins/LadspaEffect/swh/ladspa/gverb/gverbdsp.c \
    plugins/LadspaEffect/swh/ladspa/util/blo.c \
    plugins/LadspaEffect/swh/ladspa/util/buffer.c \
    plugins/LadspaEffect/swh/ladspa/util/db.c \
    plugins/LadspaEffect/swh/ladspa/util/iir.c \
    plugins/LadspaEffect/swh/ladspa/util/pitchscale.c \
    plugins/LadspaEffect/swh/ladspa/util/rms.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_autopan.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_chorusflanger.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_deesser.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_doubler.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_dynamics_m.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_dynamics_st.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_echo.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_eq.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_eqbw.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_limiter.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_pinknoise.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_pitch.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_reflector.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_reverb.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_rotspeak.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_sigmoid.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_tremolo.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_tubewarmth.c \
    plugins/LadspaEffect/tap/tap-plugins/tap_vibrato.c \
    plugins/OpulenZ/adplug/adplugdb/getopt.c \
    plugins/OpulenZ/adplug/src/adlibemu.c \
    plugins/OpulenZ/adplug/src/debug.c \
    plugins/OpulenZ/adplug/src/fmopl.c \
    plugins/OpulenZ/adplug/src/nukedopl.c \
    plugins/ReverbSC/base.c \
    plugins/ReverbSC/dcblock.c \
    plugins/ReverbSC/revsc.c

HEADERS += \
    mainwindow.h \
    include/AboutDialog.h \
    include/ActionGroup.h \
    include/aeffectx.h \
    include/AudioAlsa.h \
    include/AudioAlsaSetupWidget.h \
    include/AudioDevice.h \
    include/AudioDeviceSetupWidget.h \
    include/AudioDummy.h \
    include/AudioFileDevice.h \
    include/AudioFileFlac.h \
    include/AudioFileMP3.h \
    include/AudioFileOgg.h \
    include/AudioFileWave.h \
    include/AudioJack.h \
    include/AudioOss.h \
    include/AudioPort.h \
    include/AudioPortAudio.h \
    include/AudioPulseAudio.h \
    include/AudioSampleRecorder.h \
    include/AudioSdl.h \
    include/AudioSndio.h \
    include/AudioSoundIo.h \
    include/AutomatableButton.h \
    include/AutomatableModel.h \
    include/AutomatableModelView.h \
    include/AutomatableSlider.h \
    include/AutomationEditor.h \
    include/AutomationPattern.h \
    include/AutomationPatternView.h \
    include/AutomationTrack.h \
    include/BandLimitedWave.h \
    include/base64.h \
    include/BasicFilters.h \
    include/BBEditor.h \
    include/BBTrack.h \
    include/BBTrackContainer.h \
    include/BufferManager.h \
    include/CaptionMenu.h \
    include/Clipboard.h \
    include/ComboBox.h \
    include/ComboBoxModel.h \
    include/ConfigManager.h \
    include/Controller.h \
    include/ControllerConnection.h \
    include/ControllerConnectionDialog.h \
    include/ControllerDialog.h \
    include/ControllerRackView.h \
    include/ControllerView.h \
    include/CPULoadWidget.h \
    include/DataFile.h \
    include/debug.h \
    include/Delay.h \
    include/denormals.h \
    include/DetuningHelper.h \
    include/DrumSynth.h \
    include/DspEffectLibrary.h \
    include/DummyEffect.h \
    include/DummyInstrument.h \
    include/DummyPlugin.h \
    include/Editor.h \
    include/Effect.h \
    include/EffectChain.h \
    include/EffectControlDialog.h \
    include/EffectControls.h \
    include/EffectRackView.h \
    include/EffectSelectDialog.h \
    include/EffectView.h \
    include/embed.h \
    include/endian_handling.h \
    include/Engine.h \
    include/EnvelopeAndLfoParameters.h \
    include/EnvelopeAndLfoView.h \
    include/ExportFilter.h \
    include/ExportProjectDialog.h \
    include/FadeButton.h \
    include/Fader.h \
    include/fenv.h \
    include/fft_helpers.h \
    include/fifo_buffer.h \
    include/FileBrowser.h \
    include/FileDialog.h \
    include/FxLine.h \
    include/FxLineLcdSpinBox.h \
    include/FxMixer.h \
    include/FxMixerView.h \
    include/Graph.h \
    include/GroupBox.h \
    include/gui_templates.h \
    include/GuiApplication.h \
    include/ImportFilter.h \
    include/InlineAutomation.h \
    include/Instrument.h \
    include/InstrumentFunctions.h \
    include/InstrumentFunctionViews.h \
    include/InstrumentMidiIOView.h \
    include/InstrumentPlayHandle.h \
    include/InstrumentSoundShaping.h \
    include/InstrumentSoundShapingView.h \
    include/InstrumentTrack.h \
    include/InstrumentView.h \
    include/interpolation.h \
    include/IoHelper.h \
    include/JournallingObject.h \
    include/Knob.h \
    include/ladspa.h \
    include/Ladspa2LMMS.h \
    include/LadspaBase.h \
    include/LadspaControl.h \
    include/LadspaControlView.h \
    include/LadspaManager.h \
    include/LcdSpinBox.h \
    include/LcdWidget.h \
    include/LedCheckbox.h \
    include/LeftRightNav.h \
    include/LfoController.h \
    include/lmms_basics.h \
    include/lmms_constants.h \
    include/lmms_math.h \
    include/LmmsPalette.h \
    include/LmmsStyle.h \
    include/LocaleHelper.h \
    include/LocklessAllocator.h \
    include/LocklessList.h \
    include/LocklessRingBuffer.h \
    include/MainApplication.h \
    include/MainWindow.h \
    include/MemoryHelper.h \
    include/MemoryManager.h \
    include/MeterDialog.h \
    include/MeterModel.h \
    include/MicroTimer.h \
    include/Midi.h \
    include/MidiAlsaRaw.h \
    include/MidiAlsaSeq.h \
    include/MidiApple.h \
    include/MidiClient.h \
    include/MidiController.h \
    include/MidiDummy.h \
    include/MidiEvent.h \
    include/MidiEventProcessor.h \
    include/MidiJack.h \
    include/MidiOss.h \
    include/MidiPort.h \
    include/MidiPortMenu.h \
    include/MidiSetupWidget.h \
    include/MidiSndio.h \
    include/MidiTime.h \
    include/MidiWinMM.h \
    include/Mixer.h \
    include/MixerProfiler.h \
    include/MixerWorkerThread.h \
    include/MixHelpers.h \
    include/Model.h \
    include/ModelView.h \
    include/ModelVisitor.h \
    include/Note.h \
    include/NotePlayHandle.h \
    include/NStateButton.h \
    include/Oscillator.h \
    include/OutputSettings.h \
    include/panning.h \
    include/panning_constants.h \
    include/Pattern.h \
    include/PeakController.h \
    include/PerfLog.h \
    include/Piano.h \
    include/PianoRoll.h \
    include/PianoView.h \
    include/Pitch.h \
    include/PixmapButton.h \
    include/PlayHandle.h \
    include/Plugin.h \
    include/PluginBrowser.h \
    include/PluginFactory.h \
    include/PluginIssue.h \
    include/PluginView.h \
    include/PresetPreviewPlayHandle.h \
    include/ProjectJournal.h \
    include/ProjectNotes.h \
    include/ProjectRenderer.h \
    include/ProjectVersion.h \
    include/RecentProjectsMenu.h \
    include/RemotePlugin.h \
    include/RenameDialog.h \
    include/RenderManager.h \
    include/RingBuffer.h \
    include/RmsHelper.h \
    include/RowTableView.h \
    include/Rubberband.h \
    include/SampleBuffer.h \
    include/SamplePlayHandle.h \
    include/SampleRecordHandle.h \
    include/SampleTrack.h \
    include/SendButtonIndicator.h \
    include/SerializingObject.h \
    include/SetupDialog.h \
    include/shared_object.h \
    include/SideBar.h \
    include/SideBarWidget.h \
    include/Song.h \
    include/SongEditor.h \
    include/stdshims.h \
    include/StepRecorder.h \
    include/StepRecorderWidget.h \
    include/StringPairDrag.h \
    include/SubWindow.h \
    include/SweepOscillator.h \
    include/TabBar.h \
    include/TabButton.h \
    include/TabWidget.h \
    include/TemplatesMenu.h \
    include/TempoSyncKnob.h \
    include/TempoSyncKnobModel.h \
    include/TextFloat.h \
    include/ThreadableJob.h \
    include/TimeDisplayWidget.h \
    include/TimeLineWidget.h \
    include/ToolButton.h \
    include/ToolPlugin.h \
    include/ToolPluginView.h \
    include/ToolTip.h \
    include/Track.h \
    include/TrackContainer.h \
    include/TrackContainerView.h \
    include/TrackLabelButton.h \
    include/TrackRenameLineEdit.h \
    include/ValueBuffer.h \
    include/VersionedSaveDialog.h \
    include/versioninfo.h \
    include/VisualizationWidget.h \
    include/volume.h \
    include/VstSyncController.h \
    include/VstSyncData.h \
    plugins/Amplifier/Amplifier.h \
    plugins/Amplifier/AmplifierControlDialog.h \
    plugins/Amplifier/AmplifierControls.h \
    plugins/Amplifier/plugin_export.h \
    plugins/audio_file_processor/audio_file_processor.h \
    plugins/audio_file_processor/plugin_export.h \
    plugins/BassBooster/BassBooster.h \
    plugins/BassBooster/BassBoosterControlDialog.h \
    plugins/BassBooster/BassBoosterControls.h \
    plugins/BassBooster/plugin_export.h \
    plugins/bit_invader/bit_invader.h \
    plugins/bit_invader/plugin_export.h \
    plugins/Bitcrush/Bitcrush.h \
    plugins/Bitcrush/BitcrushControlDialog.h \
    plugins/Bitcrush/BitcrushControls.h \
    plugins/Bitcrush/plugin_export.h \
    plugins/carlabase/carla.h \
    plugins/carlabase/plugin_export.h \
    plugins/carlapatchbay/plugin_export.h \
    plugins/carlarack/plugin_export.h \
    plugins/CrossoverEQ/CrossoverEQ.h \
    plugins/CrossoverEQ/CrossoverEQControlDialog.h \
    plugins/CrossoverEQ/CrossoverEQControls.h \
    plugins/CrossoverEQ/plugin_export.h \
    plugins/Delay/DelayControls.h \
    plugins/Delay/DelayControlsDialog.h \
    plugins/Delay/DelayEffect.h \
    plugins/Delay/Lfo.h \
    plugins/Delay/plugin_export.h \
    plugins/Delay/StereoDelay.h \
    plugins/DualFilter/DualFilter.h \
    plugins/DualFilter/DualFilterControlDialog.h \
    plugins/DualFilter/DualFilterControls.h \
    plugins/DualFilter/plugin_export.h \
    plugins/dynamics_processor/dynamics_processor.h \
    plugins/dynamics_processor/dynamics_processor_control_dialog.h \
    plugins/dynamics_processor/dynamics_processor_controls.h \
    plugins/dynamics_processor/plugin_export.h \
    plugins/Eq/EqControls.h \
    plugins/Eq/EqControlsDialog.h \
    plugins/Eq/EqCurve.h \
    plugins/Eq/EqEffect.h \
    plugins/Eq/EqFader.h \
    plugins/Eq/EqFilter.h \
    plugins/Eq/EqParameterWidget.h \
    plugins/Eq/EqSpectrumView.h \
    plugins/Eq/plugin_export.h \
    plugins/Flanger/FlangerControls.h \
    plugins/Flanger/FlangerControlsDialog.h \
    plugins/Flanger/FlangerEffect.h \
    plugins/Flanger/MonoDelay.h \
    plugins/Flanger/Noise.h \
    plugins/Flanger/plugin_export.h \
    plugins/Flanger/QuadratureLfo.h \
    plugins/FreeBoy/game-music-emu/demo/Wave_Writer.h \
    plugins/FreeBoy/game-music-emu/gme/Ay_Apu.h \
    plugins/FreeBoy/game-music-emu/gme/Ay_Cpu.h \
    plugins/FreeBoy/game-music-emu/gme/Ay_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/blargg_common.h \
    plugins/FreeBoy/game-music-emu/gme/blargg_config.h \
    plugins/FreeBoy/game-music-emu/gme/blargg_endian.h \
    plugins/FreeBoy/game-music-emu/gme/blargg_source.h \
    plugins/FreeBoy/game-music-emu/gme/Blip_Buffer.h \
    plugins/FreeBoy/game-music-emu/gme/Classic_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/Data_Reader.h \
    plugins/FreeBoy/game-music-emu/gme/Dual_Resampler.h \
    plugins/FreeBoy/game-music-emu/gme/Effects_Buffer.h \
    plugins/FreeBoy/game-music-emu/gme/Fir_Resampler.h \
    plugins/FreeBoy/game-music-emu/gme/Gb_Apu.h \
    plugins/FreeBoy/game-music-emu/gme/Gb_Cpu.h \
    plugins/FreeBoy/game-music-emu/gme/gb_cpu_io.h \
    plugins/FreeBoy/game-music-emu/gme/Gb_Oscs.h \
    plugins/FreeBoy/game-music-emu/gme/Gbs_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/gme.h \
    plugins/FreeBoy/game-music-emu/gme/Gme_File.h \
    plugins/FreeBoy/game-music-emu/gme/gme_types.h \
    plugins/FreeBoy/game-music-emu/gme/Gym_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/Hes_Apu.h \
    plugins/FreeBoy/game-music-emu/gme/Hes_Cpu.h \
    plugins/FreeBoy/game-music-emu/gme/hes_cpu_io.h \
    plugins/FreeBoy/game-music-emu/gme/Hes_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/Kss_Cpu.h \
    plugins/FreeBoy/game-music-emu/gme/Kss_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/Kss_Scc_Apu.h \
    plugins/FreeBoy/game-music-emu/gme/M3u_Playlist.h \
    plugins/FreeBoy/game-music-emu/gme/Multi_Buffer.h \
    plugins/FreeBoy/game-music-emu/gme/Music_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/Nes_Apu.h \
    plugins/FreeBoy/game-music-emu/gme/Nes_Cpu.h \
    plugins/FreeBoy/game-music-emu/gme/nes_cpu_io.h \
    plugins/FreeBoy/game-music-emu/gme/Nes_Fme7_Apu.h \
    plugins/FreeBoy/game-music-emu/gme/Nes_Namco_Apu.h \
    plugins/FreeBoy/game-music-emu/gme/Nes_Oscs.h \
    plugins/FreeBoy/game-music-emu/gme/Nes_Vrc6_Apu.h \
    plugins/FreeBoy/game-music-emu/gme/Nsf_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/Nsfe_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/Sap_Apu.h \
    plugins/FreeBoy/game-music-emu/gme/Sap_Cpu.h \
    plugins/FreeBoy/game-music-emu/gme/sap_cpu_io.h \
    plugins/FreeBoy/game-music-emu/gme/Sap_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/Sms_Apu.h \
    plugins/FreeBoy/game-music-emu/gme/Sms_Oscs.h \
    plugins/FreeBoy/game-music-emu/gme/Snes_Spc.h \
    plugins/FreeBoy/game-music-emu/gme/Spc_Cpu.h \
    plugins/FreeBoy/game-music-emu/gme/Spc_Dsp.h \
    plugins/FreeBoy/game-music-emu/gme/Spc_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/Spc_Filter.h \
    plugins/FreeBoy/game-music-emu/gme/Vgm_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/Vgm_Emu_Impl.h \
    plugins/FreeBoy/game-music-emu/gme/Ym2413_Emu.h \
    plugins/FreeBoy/game-music-emu/gme/Ym2612_Emu.h \
    plugins/FreeBoy/game-music-emu/player/Audio_Scope.h \
    plugins/FreeBoy/game-music-emu/player/Music_Player.h \
    plugins/FreeBoy/game-music-emu/test/Wave_Writer.h \
    plugins/FreeBoy/FreeBoy.h \
    plugins/FreeBoy/Gb_Apu_Buffer.h \
    plugins/FreeBoy/plugin_export.h \
    plugins/GigPlayer/GigPlayer.h \
    plugins/GigPlayer/PatchesDialog.h \
    plugins/GigPlayer/plugin_export.h \
    plugins/HydrogenImport/HydrogenImport.h \
    plugins/HydrogenImport/LocalFileMng.h \
    plugins/HydrogenImport/plugin_export.h \
    plugins/kicker/kicker.h \
    plugins/kicker/KickerOsc.h \
    plugins/kicker/plugin_export.h \
    plugins/ladspa_browser/ladspa_browser.h \
    plugins/ladspa_browser/ladspa_description.h \
    plugins/ladspa_browser/ladspa_port_dialog.h \
    plugins/ladspa_browser/plugin_export.h \
    plugins/LadspaEffect/calf/veal/bigbull/ttldata.h \
    plugins/LadspaEffect/calf/veal/src/calf/analyzer.h \
    plugins/LadspaEffect/calf/veal/src/calf/audio_fx.h \
    plugins/LadspaEffect/calf/veal/src/calf/benchmark.h \
    plugins/LadspaEffect/calf/veal/src/calf/biquad.h \
    plugins/LadspaEffect/calf/veal/src/calf/buffer.h \
    plugins/LadspaEffect/calf/veal/src/calf/bypass.h \
    plugins/LadspaEffect/calf/veal/src/calf/connector.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_buttons.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_combobox.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_curve.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_fader.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_frame.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_keyboard.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_knob.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_led.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_linegraph.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_meterscale.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_notebook.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_pattern.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_phasegraph.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_tube.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_tuner.h \
    plugins/LadspaEffect/calf/veal/src/calf/ctl_vumeter.h \
    plugins/LadspaEffect/calf/veal/src/calf/delay.h \
    plugins/LadspaEffect/calf/veal/src/calf/drawingutils.h \
    plugins/LadspaEffect/calf/veal/src/calf/envelope.h \
    plugins/LadspaEffect/calf/veal/src/calf/fft.h \
    plugins/LadspaEffect/calf/veal/src/calf/fixed_point.h \
    plugins/LadspaEffect/calf/veal/src/calf/giface.h \
    plugins/LadspaEffect/calf/veal/src/calf/gtk_main_win.h \
    plugins/LadspaEffect/calf/veal/src/calf/gtk_session_env.h \
    plugins/LadspaEffect/calf/veal/src/calf/gui.h \
    plugins/LadspaEffect/calf/veal/src/calf/gui_config.h \
    plugins/LadspaEffect/calf/veal/src/calf/gui_controls.h \
    plugins/LadspaEffect/calf/veal/src/calf/host_session.h \
    plugins/LadspaEffect/calf/veal/src/calf/inertia.h \
    plugins/LadspaEffect/calf/veal/src/calf/jackhost.h \
    plugins/LadspaEffect/calf/veal/src/calf/ladspa_wrap.h \
    plugins/LadspaEffect/calf/veal/src/calf/loudness.h \
    plugins/LadspaEffect/calf/veal/src/calf/lv2_atom.h \
    plugins/LadspaEffect/calf/veal/src/calf/lv2_atom_util.h \
    plugins/LadspaEffect/calf/veal/src/calf/lv2_data_access.h \
    plugins/LadspaEffect/calf/veal/src/calf/lv2_external_ui.h \
    plugins/LadspaEffect/calf/veal/src/calf/lv2_midi.h \
    plugins/LadspaEffect/calf/veal/src/calf/lv2_options.h \
    plugins/LadspaEffect/calf/veal/src/calf/lv2_progress.h \
    plugins/LadspaEffect/calf/veal/src/calf/lv2_state.h \
    plugins/LadspaEffect/calf/veal/src/calf/lv2_ui.h \
    plugins/LadspaEffect/calf/veal/src/calf/lv2_urid.h \
    plugins/LadspaEffect/calf/veal/src/calf/lv2helpers.h \
    plugins/LadspaEffect/calf/veal/src/calf/lv2wrap.h \
    plugins/LadspaEffect/calf/veal/src/calf/metadata.h \
    plugins/LadspaEffect/calf/veal/src/calf/modmatrix.h \
    plugins/LadspaEffect/calf/veal/src/calf/modulelist.h \
    plugins/LadspaEffect/calf/veal/src/calf/modules_comp.h \
    plugins/LadspaEffect/calf/veal/src/calf/modules_delay.h \
    plugins/LadspaEffect/calf/veal/src/calf/modules_dev.h \
    plugins/LadspaEffect/calf/veal/src/calf/modules_dist.h \
    plugins/LadspaEffect/calf/veal/src/calf/modules_filter.h \
    plugins/LadspaEffect/calf/veal/src/calf/modules_limit.h \
    plugins/LadspaEffect/calf/veal/src/calf/modules_mod.h \
    plugins/LadspaEffect/calf/veal/src/calf/modules_pitch.h \
    plugins/LadspaEffect/calf/veal/src/calf/modules_synths.h \
    plugins/LadspaEffect/calf/veal/src/calf/modules_tools.h \
    plugins/LadspaEffect/calf/veal/src/calf/multichorus.h \
    plugins/LadspaEffect/calf/veal/src/calf/onepole.h \
    plugins/LadspaEffect/calf/veal/src/calf/orfanidis_eq.h \
    plugins/LadspaEffect/calf/veal/src/calf/organ.h \
    plugins/LadspaEffect/calf/veal/src/calf/osc.h \
    plugins/LadspaEffect/calf/veal/src/calf/osctl.h \
    plugins/LadspaEffect/calf/veal/src/calf/plugin_tools.h \
    plugins/LadspaEffect/calf/veal/src/calf/preset.h \
    plugins/LadspaEffect/calf/veal/src/calf/preset_gui.h \
    plugins/LadspaEffect/calf/veal/src/calf/primitives.h \
    plugins/LadspaEffect/calf/veal/src/calf/session_mgr.h \
    plugins/LadspaEffect/calf/veal/src/calf/synth.h \
    plugins/LadspaEffect/calf/veal/src/calf/utils.h \
    plugins/LadspaEffect/calf/veal/src/calf/vumeter.h \
    plugins/LadspaEffect/calf/veal/src/calf/wave.h \
    plugins/LadspaEffect/calf/veal/src/calf/waveshaping.h \
    plugins/LadspaEffect/calf/veal/src/calf/wavetable.h \
    plugins/LadspaEffect/calf/config.h \
    plugins/LadspaEffect/caps/dsp/tonestack/ks_tab.h \
    plugins/LadspaEffect/caps/dsp/tonestack/tables.h \
    plugins/LadspaEffect/caps/dsp/tonestack/vs_tab.h \
    plugins/LadspaEffect/caps/dsp/BiQuad.h \
    plugins/LadspaEffect/caps/dsp/Delay.h \
    plugins/LadspaEffect/caps/dsp/Eq.h \
    plugins/LadspaEffect/caps/dsp/FIR.h \
    plugins/LadspaEffect/caps/dsp/FPTruncateMode.h \
    plugins/LadspaEffect/caps/dsp/LatFilt.h \
    plugins/LadspaEffect/caps/dsp/Lorenz.h \
    plugins/LadspaEffect/caps/dsp/OnePole.h \
    plugins/LadspaEffect/caps/dsp/r12ax7.h \
    plugins/LadspaEffect/caps/dsp/RBJ.h \
    plugins/LadspaEffect/caps/dsp/RMS.h \
    plugins/LadspaEffect/caps/dsp/Roessler.h \
    plugins/LadspaEffect/caps/dsp/sinc.h \
    plugins/LadspaEffect/caps/dsp/Sine.h \
    plugins/LadspaEffect/caps/dsp/SVF.h \
    plugins/LadspaEffect/caps/dsp/TDFII.h \
    plugins/LadspaEffect/caps/dsp/ToneStack.h \
    plugins/LadspaEffect/caps/dsp/TwelveAX7.h \
    plugins/LadspaEffect/caps/dsp/util.h \
    plugins/LadspaEffect/caps/dsp/VCO.h \
    plugins/LadspaEffect/caps/dsp/White.h \
    plugins/LadspaEffect/caps/dsp/windows.h \
    plugins/LadspaEffect/caps/waves/click.h \
    plugins/LadspaEffect/caps/waves/money.h \
    plugins/LadspaEffect/caps/Amp.h \
    plugins/LadspaEffect/caps/basics.h \
    plugins/LadspaEffect/caps/Cabinet-Models32.h \
    plugins/LadspaEffect/caps/Cabinet.h \
    plugins/LadspaEffect/caps/Chorus.h \
    plugins/LadspaEffect/caps/Click.h \
    plugins/LadspaEffect/caps/Clip.h \
    plugins/LadspaEffect/caps/Compress.h \
    plugins/LadspaEffect/caps/Descriptor.h \
    plugins/LadspaEffect/caps/elev0.h \
    plugins/LadspaEffect/caps/Eq.h \
    plugins/LadspaEffect/caps/HRTF.h \
    plugins/LadspaEffect/caps/Lorenz.h \
    plugins/LadspaEffect/caps/Pan.h \
    plugins/LadspaEffect/caps/Phaser.h \
    plugins/LadspaEffect/caps/Reverb.h \
    plugins/LadspaEffect/caps/Roessler.h \
    plugins/LadspaEffect/caps/Scape.h \
    plugins/LadspaEffect/caps/Sin.h \
    plugins/LadspaEffect/caps/SweepVF.h \
    plugins/LadspaEffect/caps/ToneStack.h \
    plugins/LadspaEffect/caps/VCO.h \
    plugins/LadspaEffect/caps/White.h \
    plugins/LadspaEffect/cmt/src/freeverb/Components/allpass.h \
    plugins/LadspaEffect/cmt/src/freeverb/Components/comb.h \
    plugins/LadspaEffect/cmt/src/freeverb/Components/denormals.h \
    plugins/LadspaEffect/cmt/src/freeverb/Components/revmodel.h \
    plugins/LadspaEffect/cmt/src/freeverb/Components/tuning.h \
    plugins/LadspaEffect/cmt/src/cmt.h \
    plugins/LadspaEffect/cmt/src/ladspa_types.h \
    plugins/LadspaEffect/cmt/src/pinknoise.h \
    plugins/LadspaEffect/cmt/src/run_adding.h \
    plugins/LadspaEffect/cmt/src/utils.h \
    plugins/LadspaEffect/swh/ladspa/gsm/config.h \
    plugins/LadspaEffect/swh/ladspa/gsm/gsm.h \
    plugins/LadspaEffect/swh/ladspa/gsm/private.h \
    plugins/LadspaEffect/swh/ladspa/gsm/proto.h \
    plugins/LadspaEffect/swh/ladspa/gsm/unproto.h \
    plugins/LadspaEffect/swh/ladspa/gverb/gverb.h \
    plugins/LadspaEffect/swh/ladspa/gverb/gverbdsp.h \
    plugins/LadspaEffect/swh/ladspa/impulses/01-unit.h \
    plugins/LadspaEffect/swh/ladspa/impulses/02-steves-flat.h \
    plugins/LadspaEffect/swh/ladspa/impulses/03-stk-m1.h \
    plugins/LadspaEffect/swh/ladspa/impulses/04-fender-68-vibrolux-sm57.h \
    plugins/LadspaEffect/swh/ladspa/impulses/05-fender-68-vibrolux-sm57-off.h \
    plugins/LadspaEffect/swh/ladspa/impulses/06-fender-68-vibrolux-at4050.h \
    plugins/LadspaEffect/swh/ladspa/impulses/07-fender-68-vibrolux-ui87.h \
    plugins/LadspaEffect/swh/ladspa/impulses/08-fender-bassman-sm57.h \
    plugins/LadspaEffect/swh/ladspa/impulses/09-fender-bassman-sm57-off.h \
    plugins/LadspaEffect/swh/ladspa/impulses/10-fender-bassman-at4050.h \
    plugins/LadspaEffect/swh/ladspa/impulses/11-fender-bassman-ui87.h \
    plugins/LadspaEffect/swh/ladspa/impulses/12-fender-superchamp-sm57.h \
    plugins/LadspaEffect/swh/ladspa/impulses/13-fender-superchamp-sm57-off.h \
    plugins/LadspaEffect/swh/ladspa/impulses/14-fender-superchamp-at4050.h \
    plugins/LadspaEffect/swh/ladspa/impulses/15-fender-superchamp-ui87.h \
    plugins/LadspaEffect/swh/ladspa/impulses/16-marshall-jcm2000-sm57.h \
    plugins/LadspaEffect/swh/ladspa/impulses/17-marshall-jcm2000-sm57-off.h \
    plugins/LadspaEffect/swh/ladspa/impulses/18-marshall-plexi-sm57.h \
    plugins/LadspaEffect/swh/ladspa/impulses/19-marshall-plexi-sm57-off.h \
    plugins/LadspaEffect/swh/ladspa/impulses/20-matchless-chieftain-sm57.h \
    plugins/LadspaEffect/swh/ladspa/impulses/21-matchless-chieftain-sm57-off.h \
    plugins/LadspaEffect/swh/ladspa/impulses/all.h \
    plugins/LadspaEffect/swh/ladspa/util/biquad.h \
    plugins/LadspaEffect/swh/ladspa/util/blo.h \
    plugins/LadspaEffect/swh/ladspa/util/buffer.h \
    plugins/LadspaEffect/swh/ladspa/util/db.h \
    plugins/LadspaEffect/swh/ladspa/util/iir.h \
    plugins/LadspaEffect/swh/ladspa/util/ls_filter.h \
    plugins/LadspaEffect/swh/ladspa/util/pitchscale.h \
    plugins/LadspaEffect/swh/ladspa/util/rms.h \
    plugins/LadspaEffect/swh/ladspa/util/waveguide_nl.h \
    plugins/LadspaEffect/swh/ladspa/acconfig.h \
    plugins/LadspaEffect/swh/ladspa/config.h \
    plugins/LadspaEffect/swh/ladspa/ladspa-util.h \
    plugins/LadspaEffect/swh/ladspa/ladspa.h \
    plugins/LadspaEffect/tap/tap-plugins/ladspa.h \
    plugins/LadspaEffect/tap/tap-plugins/tap_dynamics_presets.h \
    plugins/LadspaEffect/tap/tap-plugins/tap_reverb.h \
    plugins/LadspaEffect/tap/tap-plugins/tap_reverb_presets.h \
    plugins/LadspaEffect/tap/tap-plugins/tap_utils.h \
    plugins/LadspaEffect/LadspaControlDialog.h \
    plugins/LadspaEffect/LadspaControls.h \
    plugins/LadspaEffect/LadspaEffect.h \
    plugins/LadspaEffect/LadspaSubPluginFeatures.h \
    plugins/LadspaEffect/plugin_export.h \
    plugins/lb302/lb302.h \
    plugins/lb302/plugin_export.h \
    plugins/MidiExport/MidiExport.h \
    plugins/MidiExport/MidiFile.hpp \
    plugins/MidiExport/plugin_export.h \
    plugins/MidiImport/portsmf/algrd_internal.h \
    plugins/MidiImport/portsmf/algsmfrd_internal.h \
    plugins/MidiImport/portsmf/allegro.h \
    plugins/MidiImport/portsmf/mfmidi.h \
    plugins/MidiImport/portsmf/strparse.h \
    plugins/MidiImport/portsmf/trace.h \
    plugins/MidiImport/MidiImport.h \
    plugins/MidiImport/plugin_export.h \
    plugins/monstro/Monstro.h \
    plugins/monstro/plugin_export.h \
    plugins/MultitapEcho/MultitapEcho.h \
    plugins/MultitapEcho/MultitapEchoControlDialog.h \
    plugins/MultitapEcho/MultitapEchoControls.h \
    plugins/MultitapEcho/plugin_export.h \
    plugins/nes/Nes.h \
    plugins/nes/plugin_export.h \
    plugins/OpulenZ/adplug/adplugdb/mygetopt.h \
    plugins/OpulenZ/adplug/src/a2m.h \
    plugins/OpulenZ/adplug/src/adl.h \
    plugins/OpulenZ/adplug/src/adlib.h \
    plugins/OpulenZ/adplug/src/adlibemu.h \
    plugins/OpulenZ/adplug/src/adplug.h \
    plugins/OpulenZ/adplug/src/adtrack.h \
    plugins/OpulenZ/adplug/src/amd.h \
    plugins/OpulenZ/adplug/src/analopl.h \
    plugins/OpulenZ/adplug/src/bam.h \
    plugins/OpulenZ/adplug/src/bmf.h \
    plugins/OpulenZ/adplug/src/cff.h \
    plugins/OpulenZ/adplug/src/cmf.h \
    plugins/OpulenZ/adplug/src/cmfmcsop.h \
    plugins/OpulenZ/adplug/src/d00.h \
    plugins/OpulenZ/adplug/src/database.h \
    plugins/OpulenZ/adplug/src/debug.h \
    plugins/OpulenZ/adplug/src/dfm.h \
    plugins/OpulenZ/adplug/src/diskopl.h \
    plugins/OpulenZ/adplug/src/dmo.h \
    plugins/OpulenZ/adplug/src/dro.h \
    plugins/OpulenZ/adplug/src/dro2.h \
    plugins/OpulenZ/adplug/src/dtm.h \
    plugins/OpulenZ/adplug/src/emuopl.h \
    plugins/OpulenZ/adplug/src/flash.h \
    plugins/OpulenZ/adplug/src/fmc.h \
    plugins/OpulenZ/adplug/src/fmopl.h \
    plugins/OpulenZ/adplug/src/fprovide.h \
    plugins/OpulenZ/adplug/src/got.h \
    plugins/OpulenZ/adplug/src/hsc.h \
    plugins/OpulenZ/adplug/src/hsp.h \
    plugins/OpulenZ/adplug/src/hybrid.h \
    plugins/OpulenZ/adplug/src/hyp.h \
    plugins/OpulenZ/adplug/src/imf.h \
    plugins/OpulenZ/adplug/src/jbm.h \
    plugins/OpulenZ/adplug/src/kemuopl.h \
    plugins/OpulenZ/adplug/src/ksm.h \
    plugins/OpulenZ/adplug/src/lds.h \
    plugins/OpulenZ/adplug/src/mad.h \
    plugins/OpulenZ/adplug/src/mdi.h \
    plugins/OpulenZ/adplug/src/mid.h \
    plugins/OpulenZ/adplug/src/mididata.h \
    plugins/OpulenZ/adplug/src/mkj.h \
    plugins/OpulenZ/adplug/src/msc.h \
    plugins/OpulenZ/adplug/src/mtk.h \
    plugins/OpulenZ/adplug/src/mus.h \
    plugins/OpulenZ/adplug/src/nemuopl.h \
    plugins/OpulenZ/adplug/src/nukedopl.h \
    plugins/OpulenZ/adplug/src/opl.h \
    plugins/OpulenZ/adplug/src/player.h \
    plugins/OpulenZ/adplug/src/players.h \
    plugins/OpulenZ/adplug/src/protrack.h \
    plugins/OpulenZ/adplug/src/psi.h \
    plugins/OpulenZ/adplug/src/rad.h \
    plugins/OpulenZ/adplug/src/rat.h \
    plugins/OpulenZ/adplug/src/raw.h \
    plugins/OpulenZ/adplug/src/realopl.h \
    plugins/OpulenZ/adplug/src/rix.h \
    plugins/OpulenZ/adplug/src/rol.h \
    plugins/OpulenZ/adplug/src/s3m.h \
    plugins/OpulenZ/adplug/src/sa2.h \
    plugins/OpulenZ/adplug/src/silentopl.h \
    plugins/OpulenZ/adplug/src/sng.h \
    plugins/OpulenZ/adplug/src/sop.h \
    plugins/OpulenZ/adplug/src/surroundopl.h \
    plugins/OpulenZ/adplug/src/temuopl.h \
    plugins/OpulenZ/adplug/src/u6m.h \
    plugins/OpulenZ/adplug/src/vgm.h \
    plugins/OpulenZ/adplug/src/wemuopl.h \
    plugins/OpulenZ/adplug/src/woodyopl.h \
    plugins/OpulenZ/adplug/src/xad.h \
    plugins/OpulenZ/adplug/src/xsm.h \
    plugins/OpulenZ/OpulenZ.h \
    plugins/OpulenZ/plugin_export.h \
    plugins/organic/organic.h \
    plugins/organic/plugin_export.h \
    plugins/patman/patman.h \
    plugins/patman/plugin_export.h \
    plugins/peak_controller_effect/peak_controller_effect.h \
    plugins/peak_controller_effect/peak_controller_effect_control_dialog.h \
    plugins/peak_controller_effect/peak_controller_effect_controls.h \
    plugins/peak_controller_effect/plugin_export.h \
    plugins/ReverbSC/base.h \
    plugins/ReverbSC/dcblock.h \
    plugins/ReverbSC/plugin_export.h \
    plugins/ReverbSC/ReverbSC.h \
    plugins/ReverbSC/ReverbSCControlDialog.h \
    plugins/ReverbSC/ReverbSCControls.h \
    plugins/ReverbSC/revsc.h \
    plugins/sf2_player/fluidsynthshims.h \
    plugins/sf2_player/patches_dialog.h \
    plugins/sf2_player/plugin_export.h \
    plugins/sf2_player/sf2_player.h \
    plugins/sfxr/plugin_export.h \
    plugins/sfxr/sfxr.h \
    plugins/sid/envelope.h \
    plugins/sid/extfilt.h \
    plugins/sid/filter.h \
    plugins/sid/plugin_export.h \
    plugins/sid/pot.h \
    plugins/sid/sid.h \
    plugins/sid/sid_instrument.h \
    plugins/sid/siddefs.h \
    plugins/sid/spline.h \
    plugins/sid/voice.h \
    plugins/sid/wave.h \
    plugins/SpectrumAnalyzer/Analyzer.h \
    plugins/SpectrumAnalyzer/DataprocLauncher.h \
    plugins/SpectrumAnalyzer/plugin_export.h \
    plugins/SpectrumAnalyzer/SaControls.h \
    plugins/SpectrumAnalyzer/SaControlsDialog.h \
    plugins/SpectrumAnalyzer/SaProcessor.h \
    plugins/SpectrumAnalyzer/SaSpectrumView.h \
    plugins/SpectrumAnalyzer/SaWaterfallView.h \
    plugins/stereo_enhancer/plugin_export.h \
    plugins/stereo_enhancer/stereo_enhancer.h \
    plugins/stereo_enhancer/stereoenhancer_control_dialog.h \
    plugins/stereo_enhancer/stereoenhancer_controls.h \
    plugins/stereo_matrix/plugin_export.h \
    plugins/stereo_matrix/stereo_matrix.h \
    plugins/stereo_matrix/stereomatrix_control_dialog.h \
    plugins/stereo_matrix/stereomatrix_controls.h \
    plugins/stk/mallets/mallets.h \
    plugins/stk/mallets/plugin_export.h \
    plugins/triple_oscillator/plugin_export.h \
    plugins/triple_oscillator/TripleOscillator.h \
    plugins/vestige/plugin_export.h \
    plugins/vestige/vestige.h \
    plugins/vibed/nine_button_selector.h \
    plugins/vibed/plugin_export.h \
    plugins/vibed/string_container.h \
    plugins/vibed/vibed.h \
    plugins/vibed/vibrating_string.h \
    plugins/vst_base/vstbase/vstbase_export.h \
    plugins/vst_base/communication.h \
    plugins/vst_base/VstPlugin.h \
    plugins/VstEffect/plugin_export.h \
    plugins/VstEffect/VstEffect.h \
    plugins/VstEffect/VstEffectControlDialog.h \
    plugins/VstEffect/VstEffectControls.h \
    plugins/VstEffect/VstSubPluginFeatures.h \
    plugins/watsyn/plugin_export.h \
    plugins/watsyn/Watsyn.h \
    plugins/waveshaper/plugin_export.h \
    plugins/waveshaper/waveshaper.h \
    plugins/waveshaper/waveshaper_control_dialog.h \
    plugins/waveshaper/waveshaper_controls.h \
    plugins/Xpressive/exprtk/exprtk.hpp \
    plugins/Xpressive/ExprSynth.h \
    plugins/Xpressive/plugin_export.h \
    plugins/Xpressive/Xpressive.h \
    plugins/zynaddsubfx/zynaddsubfx/ExternalPrograms/Controller/Controller.h \
    plugins/zynaddsubfx/zynaddsubfx/ExternalPrograms/Spliter/Spliter.h \
    plugins/zynaddsubfx/zynaddsubfx/src/DSP/AnalogFilter.h \
    plugins/zynaddsubfx/zynaddsubfx/src/DSP/FFTwrapper.h \
    plugins/zynaddsubfx/zynaddsubfx/src/DSP/Filter.h \
    plugins/zynaddsubfx/zynaddsubfx/src/DSP/FormantFilter.h \
    plugins/zynaddsubfx/zynaddsubfx/src/DSP/SVFilter.h \
    plugins/zynaddsubfx/zynaddsubfx/src/DSP/Unison.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Alienwah.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Chorus.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Distorsion.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/DynamicFilter.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Echo.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Effect.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/EffectLFO.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/EffectMgr.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/EQ.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Phaser.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Effects/Reverb.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Bank.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Config.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Control.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Dump.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/LASHClient.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Master.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Microtonal.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Part.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/QtXmlWrapper.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Recorder.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Stereo.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/Util.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/WaveShapeSmps.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/WavFile.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Misc/XMLwrapper.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/AlsaEngine.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/AudioOut.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/Engine.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/EngineMgr.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/InMgr.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/JackEngine.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/MidiIn.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/Nio.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/NulEngine.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/OssEngine.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/OutMgr.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/PaEngine.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/SafeQueue.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/WavEngine.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/ZynSema.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Output/DSSIaudiooutput.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/ADnoteParameters.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/Controller.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/EnvelopeParams.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/FilterParams.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/LFOParams.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/PADnoteParameters.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/Presets.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/PresetsArray.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/PresetsStore.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Params/SUBnoteParameters.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/ADnote.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/Envelope.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/LFO.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/OscilGen.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/PADnote.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/Resonance.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/SUBnote.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Synth/SynthNote.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Tests/AdNoteTest.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Tests/ControllerTest.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Tests/EchoTest.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Tests/MicrotonalTest.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Tests/OscilGenTest.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Tests/PadNoteTest.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Tests/PluginTest.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Tests/RandTest.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Tests/SubNoteTest.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Tests/UnisonTest.h \
    plugins/zynaddsubfx/zynaddsubfx/src/Tests/XMLwrapperTest.h \
    plugins/zynaddsubfx/zynaddsubfx/src/UI/NioUI.h \
    plugins/zynaddsubfx/zynaddsubfx/src/UI/WidgetPDial.h \
    plugins/zynaddsubfx/zynaddsubfx/src/globals.h \
    plugins/zynaddsubfx/LocalZynAddSubFx.h \
    plugins/zynaddsubfx/plugin_export.h \
    plugins/zynaddsubfx/RemoteZynAddSubFx.h \
    plugins/zynaddsubfx/ZynAddSubFx.h \
    src/lmms_export.h \
    src/ringbuffer-config.h \
    src/ringbuffer-version.h \
    src/ringbuffer_export.h \
    lmmsconfig.h \
    lmmsversion.h

FORMS += \
    mainwindow.ui \
    mainwindow.ui \
    src/gui/dialogs/about_dialog.ui \
    src/gui/dialogs/export_project.ui \
    src/gui/Forms/EffectSelectDialog.ui


