SET(MINGW_PREFIX   /opt/mingw64)
SET(MINGW_PREFIX32 /opt/mingw32)

SET(WIN64          TRUE)

SET(CMAKE_TOOLCHAIN_FILE_32			"${CMAKE_CURRENT_LIST_DIR}/Ubuntu-MinGW-X-Trusty-32.cmake")
SET(CMAKE_PREFIX_PATH_32			"${MINGW_PREFIX32}")

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/common/Ubuntu-MinGW-X-Trusty.cmake)
