SET(CMAKE_TOOLCHAIN_FILE_32			"${CMAKE_CURRENT_LIST_DIR}/Ubuntu-MinGW-W64-32.cmake")

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/common/Win64.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/common/Ubuntu-MinGW-W64.cmake)
