// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef WidgetPDial_h
#define WidgetPDial_h
#include <FL/Fl.H>
#include <FL/Fl_Dial.H>
#include <FL/fl_draw.H>
#include <FL/Fl_Tooltip.H>
#include <math.h>
#include <string.h>
#include <stdio.h>
#include <FL/Fl_Group.H>
#include <FL/Fl_Menu_Window.H>

class TipWin : public Fl_Menu_Window {
public:
  TipWin();
  void draw();
  void value(float f);
  void setText(const char * c);
  void setTextmode();
private:
  char tip[40]; 
  bool textmode; 
  enum { max_tooltip_len = 400 }; 
  char text[max_tooltip_len]; 
};

class WidgetPDial : public Fl_Dial {
public:
  WidgetPDial(int x,int y, int w, int h, const char *label=0);
  ~WidgetPDial();
  int handle(int event);
  void drawgradient(int cx,int cy,int sx,double m1,double m2);
  void draw();
  void pdialcolor(int r,int g,int b);
  void value_cb2();
  static void value_cb(Fl_Widget*, void*data);
  void tooltip(const char * c);
private:
  bool textset; 
  bool pos; 
  double oldvalue; 
  TipWin *tipwin; 
};
#endif
