# this one is important
SET(CMAKE_SYSTEM_NAME Windows)
#this one not so much
SET(CMAKE_SYSTEM_VERSION 1)

# where is the target environment 
SET(CMAKE_FIND_ROOT_PATH	${MINGW_PREFIX})
SET(CMAKE_INSTALL_PREFIX	${MINGW_PREFIX})

SET(MINGW_TOOL_PREFIX		${MINGW_PREFIX}/bin/${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-)

# specify the cross compiler
SET(CMAKE_C_COMPILER		${MINGW_TOOL_PREFIX}gcc)
SET(CMAKE_CXX_COMPILER		${MINGW_TOOL_PREFIX}g++)

# specify location of some tools
SET(STRIP					${MINGW_TOOL_PREFIX}strip)
SET(WINDRES					${MINGW_TOOL_PREFIX}windres)
SET(PKG_CONFIG_EXECUTABLE	${MINGW_TOOL_PREFIX}pkg-config)

SET(QT_BINARY_DIR			${MINGW_PREFIX}/bin)
SET(QT_LIBRARY_DIR			${MINGW_PREFIX}/lib)
SET(QT_QTCORE_LIBRARY		${MINGW_PREFIX}/lib/libQtCore4.a)
SET(QT_INCLUDE_DIR			${MINGW_PREFIX}/include/qt4)
SET(QT_HEADERS_DIR			${MINGW_PREFIX}/include/qt4)
SET(QT_QTCORE_INCLUDE_DIR	${MINGW_PREFIX}/include/qt4/QtCore)
SET(QT_MKSPECS_DIR			${MINGW_PREFIX}/share/qt4/mkspecs)
SET(QT_MOC_EXECUTABLE		${QT_BINARY_DIR}/moc.exe)
SET(QT_RCC_EXECUTABLE		${QT_BINARY_DIR}/rcc.exe)
SET(QT_QMAKE_EXECUTABLE		/usr/bin/qmake)
SET(QT_UIC_EXECUTABLE		${QT_BINARY_DIR}/uic.exe)

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

INCLUDE_DIRECTORIES(${MINGW_PREFIX}/include)
LINK_DIRECTORIES(${MINGW_PREFIX}/lib ${MINGW_PREFIX}/bin)

