name: check-strings

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install python-tinycss2
      run: sudo apt-get install -y python3-tinycss2
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Verify check-strings script
      run: tests/check-strings/verify
    - name: Run check-strings
      run: tests/check-strings/check-strings
