---
name: doxygen
'on': [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  linux-x86_64:
    name: linux-x86_64
    runs-on: ubuntu-22.04
    env:
      CMAKE_OPTS: >-
        -DUSE_WERROR=ON
        -DUSE_COMPILE_CACHE=ON
        -DWANT_DEBUG_CPACK=ON
      MAKEFLAGS: -j2
    steps:
      - name: Configure git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends binutils doxygen
          sudo apt-get install -y --no-install-recommends $(xargs < .github/workflows/deps-ubuntu-24.04-gcc.txt)
      - name: Configure
        run: |
          source /opt/qt5*/bin/qt5*-env.sh || true
          cmake -S . -B build $CMAKE_OPTS
      - name: Build docs
        run: cmake --build build --target doc
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload generated website
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/doc/doc/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
