---
name: doxygen
'on': [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  linux-x86_64:
    name: linux-x86_64
    runs-on: ubuntu-22.04
    env:
      CMAKE_OPTS: >-
        -DUSE_WERROR=ON
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DUSE_COMPILE_CACHE=ON
        -DWANT_DEBUG_CPACK=ON
      CCACHE_MAXSIZE: 0
      CCACHE_NOCOMPRESS: 1
      MAKEFLAGS: -j2
    steps:
      - name: Configure git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Clone fltk
        uses: actions/checkout@v4
        with:
          repository: fltk/fltk
          path: fltk
          ref: 27d991f046bdebb12bfd58f7c05a19f135979c29
          fetch-depth: 1
      - name: Configure winehq
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          wget -O - https://dl.winehq.org/wine-builds/winehq.key | \
          sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
          sudo wget -NP /etc/apt/sources.list.d/ \
          https://dl.winehq.org/wine-builds/ubuntu/dists/$(lsb_release -cs)/winehq-$(lsb_release -cs).sources
      - name: Install packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --install-recommends doxygen
          sudo apt-get install -y --no-install-recommends \
            $(xargs < .github/workflows/deps-ubuntu-24.04-gcc.txt)
          sudo apt-get install -y --install-recommends g++-multilib gcc-multilib winehq-devel wine-devel-dev
          sudo apt-get install -y --install-recommends \
            $(xargs < .github/workflows/deps-ubuntu-24.04-fltk.txt)
      - name: Configure fltk
        run: |
          cmake -S fltk -B fltk/build -DFLTK_BUILD_SHARED_LIBS=ON -DFLTK_BACKEND_WAYLAND=ON \
            -DFLTK_USE_LIBDECOR_GTK=OFF -DFLTK_BUILD_TEST=OFF -DFLTK_BUILD_GL=OFF
      - name: Install fltk
        run: |
          cmake --build fltk/build
          sudo cmake --install fltk/build --prefix /usr
      - name: Configure
        run: |
          source /opt/qt5*/bin/qt5*-env.sh || true
          cmake -S . -B build $CMAKE_OPTS
      - name: Build docs
        run: cmake --build build --target doc
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload generated website
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/doc/doc/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
